prompt_name: historic_budgets.j2
ndatapoints: 500
output_file: historic_data.json
required_fields: 
  - email_subject
  - email_body
  - caracteristics

prompt_parameters:
  type_of_business: window framing
  feature_list:
    - quantity
    - length
    - height
    - color
    - material
    - finish
    - glass_type